name: "Tagged Linux Release"

on:
  push:
    tags:
      - "v*"

jobs:
  build-release:
    name: "Release"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt
      - name: Build with pyinstaller
        run: |
          pyinstaller --onefile Skout.py

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist/Skout
            example.skout.json
            skout.schema.json